# Homebrew alias
alias brewlib="cd ${BREW_HOME}/Cellar/"
alias bi="brew install"
alias bl="brew list"
alias bo="brew outdated"
alias bup="brew update"
alias bug="brew upgrade"
alias bs="brew search"
alias bf="brew info"
